spring:
  application:
      name: task-vacation-impl


camunda:
  client:
    mode: selfManaged
    auth:
      client-id: "todo"
      client-secret: "todo"
      issuer: "todo"
    zeebe:
      enabled: true
      audience: zeebe-api
      rest-address: "todo"
      grpc-address: "todo"
      execution-threads: 3
      keep-alive: 50s
      message-time-to-live: 15s


erp:
  baseUrl: "todo"
