apiVersion: v1
kind: Secret
metadata:
  name: "camunda-static-secret"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:{{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- with .Values.staticSecret }}
  keycloak-admin-password: {{ .keycloakAdminPassword | quote }}
  identity-firstuser-password: {{ .identityFirstUserPassword | quote }}
  operate-secret: {{ .operateKeycloakClientSecret | quote }}
  tasklist-secret: {{ .tasklistKeycloakClientSecret | quote }}
  optimize-secret: {{ .optimizeKeycloakClientSecret | quote }}
  connectors-secret: {{ .connectorsKeycloakClientSecret | quote }}
  zeebe-secret: {{ .zeebeKeycloakClientSecret | quote }}
  {{- end }}
  elasticsearch-password: {{ .Values.camunda.elasticsearch.security.elasticPassword | quote }}
